@port = 3003
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QxIiwiaWQiOiI2MDFiMDAzNWNmOGI5YzM4MzZlMDhkOTgiLCJpYXQiOjE2MTY0NDI3Njl9.OGNJ3msjPghSgoNap2bEftvHFXCj0SlngUO8yW2dbLk
@blog = 6057aec0445d983f6710d5ef
###
http://localhost:{{port}}/api/blogs HTTP/1.1
###
POST http://localhost:{{port}}/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "title": "Root kolmoset blogi kakkonen",
    "author": "bluu",
    "url": "blaa",
    "likes": "123"
}
###
http://localhost:{{port}}/api/users HTTP/1.1
###
POST http://localhost:{{port}}/api/users HTTP/1.1
content-type: application/json

{
    "username": "root3",
    "name": "Superuser",
    "password": "salainen"
}
###
POST http://localhost:{{port}}/api/login HTTP/1.1
content-type: application/json

{
    "username": "root1",
    "password": "salainen"
}
###
DELETE http://localhost:{{port}}/api/blogs/{{blog}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
###
POST http://localhost:{{port}}/api/testing/reset HTTP/1.1
content-type: application/json
###
POST http://localhost:{{port}}/api/blogs/{{blog}}/comments HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "text": "kommentti 7. Lue minut!"
}